//generated by lazy
//author: seanlan

package service

import (
	"context"
	"github.com/seanlan/xlvein/app/model"
)

func HealthCheck(ctx context.Context, userID int64, req model.HealthCheckReq) (err error, resp model.HealthCheckResp) {
	return
}
