//generated by lazy
//author: seanlan

package service

import (
	"context"
	"github.com/seanlan/xlvein/app/model"
)

func CreateConversation(ctx context.Context, req model.CreateConversationReq) (resp model.CreateConversationResp, err error) {
	return
}
