//generated by lazy
//author: seanlan

package v1

import (
	"github.com/gin-gonic/gin"
	"github.com/seanlan/xlvein/internal/model"
	"github.com/seanlan/xlvein/internal/service"
	"github.com/seanlan/xlvein/pkg/xlhttp"
)

func PushMessage(c *gin.Context) {
	var (
		err error
	)
	r := xlhttp.Build(c)
	var req model.PushMessageReq
	err = r.RequestParser(&req)
	if err != nil {
		return
	}
	req.ClientIP = c.ClientIP()
	resp, err := service.PushMessage(c, req)
	r.JsonReturn(err, resp)
	return
}
