//generated by lazy
//author: seanlan

package v1

import (
	"github.com/gin-gonic/gin"
	"github.com/seanlan/goutils/xlerror"
	"github.com/seanlan/goutils/xlhttp"
	"github.com/seanlan/xlvein/app/model"
	"github.com/seanlan/xlvein/app/service"
)

func HealthCheck(c *gin.Context) {
	var (
		err    error
		userID int64
	)
	r := xlhttp.Build(c)
	userID, err = r.GetJWTUID()
	if userID == 0 || err != nil {
		r.JsonReturn(xlerror.ErrToken)
		return
	}
	var req model.HealthCheckReq
	err = r.RequestParser(&req)
	if err != nil {
		return
	}
	err, resp := service.HealthCheck(c, userID, req)
	r.JsonReturn(err, resp)
	return
}
