//generated by lazy
//author: seanlan

package model

type SocketConnectReq struct {
	Token string `query:"" form:"token" json:"token" binding:"required"`
	AppID string `form:"app_id" json:"app_id" binding:"required"`
}

type SocketConnectResp struct {
}
