//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameApplication = "application"

var ApplicationColumns = struct {
	AppID     FieldBase
	AppSecret FieldBase
	CreateAt  FieldBase
	ID        FieldBase
	NotifyURL FieldBase
	Whitelist FieldBase
}{
	AppID:     FieldBase{"`app_id`"},
	AppSecret: FieldBase{"`app_secret`"},
	CreateAt:  FieldBase{"`create_at`"},
	ID:        FieldBase{"`id`"},
	NotifyURL: FieldBase{"`notify_url`"},
	Whitelist: FieldBase{"`whitelist`"},
}

type Application struct {
	AppID     string `json:"app_id" gorm:"column:app_id;type:varchar(128);not null"`                 //应用APPID
	AppSecret string `json:"app_secret" gorm:"column:app_secret;type:varchar(255);not null"`         //APPSECRET
	CreateAt  int64  `json:"create_at" gorm:"column:create_at;type:bigint;not null"`                 //创建时间
	ID        uint64 `json:"id" gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true"` //
	NotifyURL string `json:"notify_url" gorm:"column:notify_url;type:varchar(512);not null"`         //消息通知地址
	Whitelist string `json:"whitelist" gorm:"column:whitelist;type:varchar(512);not null"`           //白名单ID逗号分隔
}

// TableName Application's table name
func (*Application) TableName() string {
	return TableNameApplication
}
