//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameChatHistory = "chat_history"

var ChatHistoryColumns = struct {
	AppID          FieldBase
	Content        FieldBase
	ConversationID FieldBase
	Event          FieldBase
	FromTag        FieldBase
	ID             FieldBase
	MsgID          FieldBase
	SendAt         FieldBase
	ToTag          FieldBase
}{
	AppID:          FieldBase{"`app_id`"},
	Content:        FieldBase{"`content`"},
	ConversationID: FieldBase{"`conversation_id`"},
	Event:          FieldBase{"`event`"},
	FromTag:        FieldBase{"`from_tag`"},
	ID:             FieldBase{"`id`"},
	MsgID:          FieldBase{"`msg_id`"},
	SendAt:         FieldBase{"`send_at`"},
	ToTag:          FieldBase{"`to_tag`"},
}

type ChatHistory struct {
	AppID          string `json:"app_id" gorm:"column:app_id;type:varchar(128);not null"`                   //应用appid
	Content        string `json:"content" gorm:"column:content;type:varchar(1024);not null"`                //消息内容json自定义
	ConversationID string `json:"conversation_id" gorm:"column:conversation_id;type:varchar(128);not null"` //会话ID
	Event          int32  `json:"event" gorm:"column:event;type:int;not null"`                              //消息类型 1、普通消息 2、群组消息 3、入群 4、退群
	FromTag        string `json:"from_tag" gorm:"column:from_tag;type:varchar(128);not null"`               //发送方标示
	ID             uint32 `json:"id" gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true"`      //
	MsgID          string `json:"msg_id" gorm:"column:msg_id;type:varchar(128);not null"`                   //消息ID
	SendAt         int64  `json:"send_at" gorm:"column:send_at;type:bigint;not null"`                       //消息发送时间
	ToTag          string `json:"to_tag" gorm:"column:to_tag;type:varchar(128);not null"`                   //接收方标示
}

// TableName ChatHistory's table name
func (*ChatHistory) TableName() string {
	return TableNameChatHistory
}
