//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameConversation = "conversation"

var ConversationColumns = struct {
	ID             FieldBase
	AppID          FieldBase
	ConversationID FieldBase
	Name           FieldBase
	Icon           FieldBase
	MemberCount    FieldBase
	CreateAt       FieldBase
}{
	ID:             FieldBase{"`id`"},
	AppID:          FieldBase{"`app_id`"},
	ConversationID: FieldBase{"`conversation_id`"},
	Name:           FieldBase{"`name`"},
	Icon:           FieldBase{"`icon`"},
	MemberCount:    FieldBase{"`member_count`"},
	CreateAt:       FieldBase{"`create_at`"},
}

type Conversation struct {
	ID             uint64 `json:"id" gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true"`  //
	AppID          string `json:"app_id" gorm:"column:app_id;type:varchar(128);not null"`                  //应用APPID
	ConversationID string `json:"conversation_id" gorm:"column:conversation_id;type:varchar(56);not null"` //会话ID
	Name           string `json:"name" gorm:"column:name;type:varchar(56);not null"`                       //会话名称
	Icon           string `json:"icon" gorm:"column:icon;type:varchar(256);not null"`                      //会话图标
	MemberCount    int64  `json:"member_count" gorm:"column:member_count;type:bigint;not null"`            //成员数量
	CreateAt       int64  `json:"create_at" gorm:"column:create_at;type:bigint;not null"`                  //创建时间
}

// TableName Conversation's table name
func (*Conversation) TableName() string {
	return TableNameConversation
}
