//generated by lazy
//author: seanlan

package dao

import (
	"context"
	"github.com/seanlan/xlvein/app/dao/sqlmodel"
	"gorm.io/gorm/clause"
)

func CountChatHistory(ctx context.Context, expr clause.Expression) (totalRows int64, err error) {
	db := GetDB(ctx).WithContext(ctx).Model(&sqlmodel.ChatHistory{})
	if expr != nil {
		db = db.Where(expr)
	}
	db.Count(&totalRows)
	return totalRows, nil
}

func SumChatHistory(ctx context.Context, sumField sqlmodel.FieldBase, expr clause.Expression) (sum int64, err error) {
	var sumValue = struct {
		N int64 `json:"n"`
	}{}
	db := GetDB(ctx).WithContext(ctx).Model(&sqlmodel.ChatHistory{})
	if expr != nil {
		db = db.Where(expr)
	}
	err = db.Select("sum(" + sumField.FieldName + ") as n").Scan(&sumValue).Error
	return sumValue.N, err
}

func FetchAllChatHistory(ctx context.Context, records interface{}, expr clause.Expression, page, pagesize int, orders ...string) (err error) {
	db := GetDB(ctx).WithContext(ctx).Model(&sqlmodel.ChatHistory{})
	if expr != nil {
		db = db.Where(expr)
	}
	if page > 0 {
		offset := (page - 1) * pagesize
		db = db.Offset(offset).Limit(pagesize)
	} else {
		db = db.Limit(pagesize)
	}
	for _, order := range orders {
		db = db.Order(order)
	}
	if err = db.Find(records).Error; err != nil {
		err = ErrNotFound
		return err
	}
	return nil
}

func FetchChatHistory(ctx context.Context, record interface{}, expr clause.Expression, orders ...string) (err error) {
	db := GetDB(ctx).WithContext(ctx).Model(&sqlmodel.ChatHistory{})
	if expr != nil {
		db = db.Where(expr)
	}
	for _, order := range orders {
		db = db.Order(order)
	}
	if err = db.First(record).Error; err != nil {
		err = ErrNotFound
		return err
	}
	return nil
}

func AddChatHistory(ctx context.Context, d *sqlmodel.ChatHistory) (RowsAffected int64, err error) {
	db := GetDB(ctx).WithContext(ctx).Model(&sqlmodel.ChatHistory{}).Create(d)
	if err = db.Error; err != nil {
		return -1, ErrInsertFailed
	}
	return db.RowsAffected, nil
}

func AddsChatHistory(ctx context.Context, d *[]sqlmodel.ChatHistory) (RowsAffected int64, err error) {
	db := GetDB(ctx).WithContext(ctx).Model(&sqlmodel.ChatHistory{}).Create(d)
	if err = db.Error; err != nil {
		return -1, ErrInsertFailed
	}
	return db.RowsAffected, nil
}

func UpdateChatHistory(ctx context.Context, updated *sqlmodel.ChatHistory) (RowsAffected int64, err error) {
	db := GetDB(ctx).WithContext(ctx).Save(updated)
	if err = db.Error; err != nil {
		return -1, ErrUpdateFailed
	}
	return db.RowsAffected, nil
}

func UpdatesChatHistory(ctx context.Context, expr clause.Expression, updated map[string]interface{}) (RowsAffected int64, err error) {
	db := GetDB(ctx).WithContext(ctx).Model(&sqlmodel.ChatHistory{})
	if expr != nil {
		db = db.Where(expr)
	}
	db = db.Updates(updated)
	if err = db.Error; err != nil {
		return -1, err
	}
	return db.RowsAffected, nil
}

func UpsertChatHistory(ctx context.Context, d *sqlmodel.ChatHistory, upsert map[string]interface{}) (RowsAffected int64, err error) {
	db := GetDB(ctx).WithContext(ctx).Model(&sqlmodel.ChatHistory{}).Clauses(clause.OnConflict{
		DoUpdates: clause.Assignments(upsert),
	}).Create(d)
	if err = db.Error; err != nil {
		return -1, ErrInsertFailed
	}
	return db.RowsAffected, nil
}

func DeleteChatHistory(ctx context.Context, expr clause.Expression) (rowsAffected int64, err error) {
	db := GetDB(ctx).WithContext(ctx).Model(&sqlmodel.ChatHistory{})
	if expr != nil {
		db = db.Where(expr)
	}
	db = db.Delete(sqlmodel.ChatHistory{})
	if err = db.Error; err != nil {
		return -1, err
	}
	return db.RowsAffected, nil
}
