//generated by lazy
//author: seanlan

package service

import (
	"context"
	"github.com/seanlan/xlvein/internal/model"
)

func SocketConnect(ctx context.Context, userID int64, req model.SocketConnectReq) (err error, resp model.SocketConnectResp) {
	return
}
