//generated by lazy
//author: seanlan

package service

import (
	"context"
	"encoding/json"
	"github.com/seanlan/xlvein/internal/common/exchange"
	"github.com/seanlan/xlvein/internal/common/transport"
	"github.com/seanlan/xlvein/internal/config"
	"github.com/seanlan/xlvein/internal/e"
	"github.com/seanlan/xlvein/internal/model"
	"github.com/seanlan/xlvein/pkg/veinsdk"
	"time"
)

func PushMessage(ctx context.Context, req model.PushMessageReq) (resp model.PushMessageResp, err error) {
	app := config.C.GetApp(req.AppKey)
	if app == nil {
		err = e.ErrAppNotFound
		return
	}
	sdk := veinsdk.New("", req.AppKey, app.AppSecret)
	if sdk.GetSign(map[string]interface{}{
		"app_key": req.AppKey,
		"send_to": req.SendTo,
		"message": req.Message,
		"nonce":   req.Nonce,
	}) != req.Sign {
		err = e.ErrSignInvalid
		return
	}
	var msg map[string]interface{}
	err = json.Unmarshal([]byte(req.Message), &msg)
	if err != nil {
		err = e.ErrMessageInvalid
		return
	}
	transport.ClientHub.PushToExchange(
		req.AppKey,
		transport.Message{
			From:   "",
			To:     req.SendTo,
			Event:  exchange.EventSystem,
			Data:   msg,
			SendAt: time.Now().UnixMilli(),
		})
	return
}
